# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "file_gyu", "ci" ]
  pull_request:
    branches: [ "file_gyu", "ci" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Inject application.yml
      run: |
        mkdir -p ./src/main/resources && 
        echo "${{ secrets.APPLICATION_YML_TEXT }}" > ./src/main/resources/application.yml
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        gradle-version: 8.2.1
        arguments: build

    - name: Upload to the EC2 instance
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: ${{ secrets.EC2_HOST }} 
        username: ${{ secrets.EC2_USER }} 
        privateKey: ${{ secrets.EC2_SSH_PEM }} 
        localDir: 'build/libs'
        remoteDir: '/home/ubuntu/jars'
